name: Integration tests

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: false
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: false

permissions: {}

jobs:
  integration-tests-v2:
    permissions:
      contents: read
    uses: ./.github/workflows/integration-tests-v2.yml
    secrets:
        FIREBOLT_CLIENT_ID_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
        FIREBOLT_CLIENT_SECRET_STG_NEW_IDN: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}

  integration-tests-engine:
    permissions:
      contents: read
      packages: read
    uses: ./.github/workflows/integration-test-engine.yml
