name: Integration tests V2

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      FIREBOLT_CLIENT_ID_STG_NEW_IDN:
        required: false
      FIREBOLT_CLIENT_SECRET_STG_NEW_IDN:
        required: false

permissions: {}

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: "stable"
          check-latest: true

      - name: Setup database and engine
        id: setup
        uses: firebolt-db/integration-testing-setup@813c4835ef38adcba3f8760e7afc21a3c7248023 # v2.6.2
        with:
          firebolt-client-id: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
          firebolt-client-secret: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN}}
          api-endpoint: "api.staging.firebolt.io"
          account: ${{ vars.FIREBOLT_ACCOUNT }}

      - name: Run integration tests
        env:
          DATABASE_NAME: ${{ steps.setup.outputs.database_name }}
          ENGINE_NAME: ${{ steps.setup.outputs.engine_name }}
          FIREBOLT_ENDPOINT: "api.staging.firebolt.io"
          ACCOUNT_NAME: ${{ vars.FIREBOLT_ACCOUNT }}
          CLIENT_ID: ${{ secrets.FIREBOLT_CLIENT_ID_STG_NEW_IDN }}
          CLIENT_SECRET: ${{ secrets.FIREBOLT_CLIENT_SECRET_STG_NEW_IDN }}
          LONG_TEST_VALUE: ${{ vars.LONG_TEST_VALUE }}
        run: |
          go test ./... -timeout=30m -v --tags=integration
