name: Pull request

on:
  pull_request:
    branches: [ main, 1.x ]
    types: [ opened, synchronize, reopened, edited ]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check title name convention
        uses: jef/conventional-commits-pr-action@2ee589f151916f92da5e2887c38d5fe6402e803c # v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  code-checkers:
    uses: ./.github/workflows/code-check.yml
