name: v1.x Release new version

on:
  workflow_dispatch:
    inputs:
      pre-release-tag:
        required: false
        description: 'Tag for pre-release (optional)'
      major-release:
        required: false
        description: 'Trigger a major release (optional). Leave empty for regular release.'

jobs:
  release:
    uses: ./.github/workflows/release-workflow.yml
    with:
      branch: 1.x
      pre-release-tag: ${{ inputs.pre-release-tag }}
      major-release: ${{ inputs.major-release }}
    secrets: inherit
